from django.utils.translation import ugettext_lazy as _

USER_TYPE = (
        (1, _('Client')),
        (2, _('Artist')),
        (3, _('Organizer')),
    )

MUSIC_CHOICE = (
		(1, _('Rock')),
		(2, _('Pop music')),
		(3, _('Jazz')),
		(4, _('Folk music')),
		(5, _('Hip hop music')),
		(6, _('Blues')),
		(7, _('Country music')),
		(8, _('Rhythm and blues')),
		(9, _('Electronic music')),
		(10, _('Classical music')),
		(11, _('Heavy metal')),
		(12, _('Reggae')),
		(13, _('Punk rock')),
		(14, _('Funk')),
		(15, _('Singing')),
		(16, _('Soul music')),
		(17, _('Electronic dance music')),
		(18, _('Popular music')),
		(19, _('Pop rock')),
		(20, _('House music')),
		(21, _('Orchestra')),
		(22, _('Disco')),
		(23, _('Dance music')),
		(24, _('Alternative rock')),
		(25, _('World')),
		(26, _('Musical theatre')),
		(27, _('Gospel music')),
		(28, _('Techno')),
		(29, _('Easy listening')),
		(30, _('Instrumental')),
		(31, _('New-age music')),
		(32, _('Opera')),
		(33, _('Progressive rock')),
		(34, _('Trance music')),
		(35, _('Indie rock')),
		(36, _('Ambient music')),
		(37, _('Experimental music')),
		(38, _('Jazz fusion')),
		(39, _('Swing music')),
		(40, _('Hard rock')),
		(41, _('Avant-garde music')),
		(42, _('Industrial music')),
		(43, _('New wave')),
		(44, _('Dubstep')),
		(45, _('Emo')),
		(46, _('Country rock')),
		(47, _('Electro')),
		(48, _('Progressive music')),
		(49, _('Hardcore punk')),
		(50, _('Religious music')),
		(51, _('Dance-pop')),
    )

SEX = (
       (1, _('Male')),
       (2, _('Female')),
       (3, _('Prefer not to say...')),
    )
